export const pokedex = [
    {
        id: 1,
        name: 'Bulbasaur',
        type: ['Grass'],
        description: "",
        image: 'assets/pokedex/1.png',
        mega: false,
        primal: false
    },
    {
        id: 2,
        name: 'Ivysaur',
        type: ['Grass'],
        description: "",
        image: 'assets/pokedex/2.png',
        mega: false,
        primal: false
    },
    {
        id: 3,
        name: 'Venusaur',
        type: ['Grass'],
        description: "",
        image: 'assets/pokedex/3.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/3-mega.png'],
    },
    {
        id: 4,
        name: 'Charmander',
        type: ['Fire'],
        description: "",
        image: 'assets/pokedex/4.png',
        mega: false,
        primal: false
    },
    {
        id: 5,
        name: 'Charmeleon',
        description: "",
        type: ['Fire', "Flying"],
        image: 'assets/pokedex/5.png',
        mega: false,
        primal: false
    },
    {
        id: 6,
        name: 'Charizard',
        type: ['Fire'],
        description: "",
        image: 'assets/pokedex/6.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/5-Y.png', 'assets/pokedex/5-X.png']
    },
    {
        id: 7,
        name: 'Squirtle',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/7.png',
        mega: false,
        primal: false,
    },
    {
        id: 8,
        name: 'Wartortle',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/8.png',
        mega: false,
        primal: false,
    },
    {
        id: 9,
        name: 'Blastoise',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/9.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/9-mega.png']
    },
    {
        id: 25,
        name: 'Pikachu',
        description: "",
        type: ['Electric'],
        image: 'assets/pokedex/25.png',
        mega: false,
        primal: false,
    },
    {
        id: 65,
        name: 'Alakazam',
        description: "",
        type: ['Psychic'],
        image: 'assets/pokedex/65.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/65-mega.png']
    },
    {
        id: 67,
        name: 'Machamp',
        description: "",
        type: ['Fighting'],
        image: 'assets/pokedex/67.png',
        mega: false,
        primal: false,
    },
    {
        id: 94,
        name: 'Gengar',
        description: "",
        type: ['Ghost', 'Poison'],
        image: 'assets/pokedex/94.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/94-mega.png']
    },
    {
        id: 130,
        name: 'Gyarados',
        description: "",
        type: ['Water', 'Flying'],
        image: 'assets/pokedex/130.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/130-mega.png']
    },
    {
        id: 131,
        name: 'Lapras',
        description: "",
        type: ['Water', 'Ice'],
        image: 'assets/pokedex/131.png',
        mega: false,
        primal: false,
    },
    {
        id: 143,
        name: 'Snorlax',
        description: "",
        type: ['Normal'],
        image: 'assets/pokedex/143.png',
        mega: false,
        primal: false,
    },
    {
        id: 144,
        name: 'Articuno',
        description: "",
        type: ['Ice', 'Flying'],
        image: 'assets/pokedex/144.png',
        mega: false,
        primal: false,
    },
    {
        id: 145,
        name: 'Zapdos',
        description: "",
        type: ['Electric', 'Flying'],
        image: 'assets/pokedex/145.png',
        mega: false,
        primal: false,
    },
    {
        id: 146,
        name: 'Moltres',
        description: "",
        type: ['Fire', 'Flying'],
        image: 'assets/pokedex/146.png',
        mega: false,
        primal: false,
    },
    {
        id: 149,
        name: 'Dragonite',
        description: "",
        type: ['Dragon', 'Flying'],
        image: 'assets/pokedex/149.png',
        mega: false,
        primal: false,
    },
    {
        id: 150,
        name: 'Mewtwo',
        description: "",
        type: ['Psychic'],
        image: 'assets/pokedex/150.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/150-Y.png', 'assets/pokedex/150-X.png']
    },
    {
        id: 151,
        name: 'Mew',
        description: "",
        type: ['Psychic'],
        image: 'assets/pokedex/151.png',
        mega: false,
        primal: false,
    },
    {
        id: 152,
        name: 'Chikorita',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/152.png',
        mega: false,
        primal: false,
    },
    {
        id: 153,
        name: 'Bayleef',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/153.png',
        mega: false,
        primal: false,
    },
    {
        id: 154,
        name: 'Meganium',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/154.png',
        mega: false,
        primal: false,
    },
    {
        id: 155,
        name: 'Cyndaquil',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/155.png',
        mega: false,
        primal: false,
    },
    {
        id: 156,
        name: 'Quilava',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/156.png',
        mega: false,
        primal: false,
    },
    {
        id: 157,
        name: 'Typhlosion',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/157.png',
        mega: false,
        primal: false,
    },
    {
        id: 158,
        name: 'Totodile',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/158.png',
        mega: false,
        primal: false,
    },
    {
        id: 159,
        name: 'Croconaw',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/159.png',
        mega: false,
        primal: false,
    },
    {
        id: 160,
        name: 'Feraligatr',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/160.png',
        mega: false,
        primal: false,
    },
    {
        id: 212,
        name: 'Scizor',
        description: "",
        type: ['Bug', 'Steel'],
        image: 'assets/pokedex/212.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/212-mega.png']
    },
    {
        id: 214,
        name: 'Heracross',
        description: "",
        type: ['Bug', 'Fighting'],
        image: 'assets/pokedex/214.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/214-mega.png']
    },
    {
        id: 243,
        name: 'Raikou',
        description: "",
        type: ['Electric'],
        image: 'assets/pokedex/243.png',
        mega: false,
        primal: false,
    },
    {
        id: 244,
        name: 'Entei',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/244.png',
        mega: false,
        primal: false,
    },
    {
        id: 245,
        name: 'Suicune',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/245.png',
        mega: false,
        primal: false,
    },
    {
        id: 248,
        name: 'Tyranitar',
        description: "",
        type: ['Rock', 'Dark'],
        image: 'assets/pokedex/248.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/248-mega.png']
    },
    {
        id: 249,
        name: 'Lugia',
        description: "",
        type: ['Psychic', 'Flying'],
        image: 'assets/pokedex/249.png',
        mega: false,
        primal: false,
    },
    {
        id: 250,
        name: 'Ho-Oh',
        description: "",
        type: ['Fire', 'Flying'],
        image: 'assets/pokedex/250.png',
        mega: false,
        primal: false,
    },
    {
        id: 251,
        name: 'Celebi',
        description: "",
        type: ['Psychic', 'Grass'],
        image: 'assets/pokedex/251.png',
        mega: false,
        primal: false,
    },
    {
        id: 252,
        name: 'Treecko',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/252.png',
        mega: false,
        primal: false,
    },
    {
        id: 253,
        name: 'Grovyle',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/253.png',
        mega: false,
        primal: false,
    },
    {
        id: 254,
        name: 'Sceptile',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/254.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/254-mega.png']
    },
    {
        id: 255,
        name: 'Torchic',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/255.png',
        mega: false,
        primal: false,
    },
    {
        id: 256,
        name: 'Combusken',
        description: "",
        type: ['Fire', 'Fighting'],
        image: 'assets/pokedex/256.png',
        mega: false,
    },
    {
        id: 257,
        name: 'Blaziken',
        description: "",
        type: ['Fire', 'Fighting'],
        image: 'assets/pokedex/257.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/257-mega.png']
    },
    {
        id: 324,
        name: 'Torkoal',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/324.png',
        mega: false,
        primal: false,
    },
    {
        id: 330,
        name: 'Flygon',
        description: "",
        type: ['Ground', 'Dragon'],
        image: 'assets/pokedex/330.png',
        mega: false,
        primal: false,
    },
    {
        id: 373,
        name: 'Salamence',
        description: "",
        type: ['Dragon', 'Flying'],
        image: 'assets/pokedex/373.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/373-mega.png']
    },
    {
        id: 376,
        name: 'Metagross',
        description: "",
        type: ['Steel', 'Psychic'],
        image: 'assets/pokedex/376.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/376-mega.png']
    },
    {
        id: 377,
        name: 'Regirock',
        description: "",
        type: ['Rock'],
        image: 'assets/pokedex/377.png',
        mega: false,
        primal: false,
    },
    {
        id: 378,
        name: 'Regice',
        description: "",
        type: ['Ice'],
        image: 'assets/pokedex/378.png',
        mega: false,
        primal: false,
    },
    {
        id: 379,
        name: 'Registeel',
        description: "",
        type: ['Steel'],
        image: 'assets/pokedex/379.png',
        mega: false,
        primal: false,
    },
    {
        id: 380,
        name: 'Latias',
        description: "",
        type: ['Dragon', 'Psychic'],
        image: 'assets/pokedex/380.png',
        mega: false,
        primal: false,
    },
    {
        id: 381,
        name: 'Latios',
        description: "",
        type: ['Dragon', 'Psychic'],
        image: 'assets/pokedex/381.png',
        mega: false,
        primal: false,
    },
    {
        id: 382,
        name: 'Kyogre',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/382.png',
        mega: false,
        primal: true,
        primalImage: ['assets/pokedex/382-primal.png']
    },
    {
        id: 383,
        name: 'Groudon',
        description: "",
        type: ['Ground'],
        image: 'assets/pokedex/383.png',
        mega: false,
        primal: true,
        primalImage: ['assets/pokedex/383-primal.png']
    },
    {
        id: 384,
        name: 'Rayquaza',
        description: "",
        type: ['Dragon', 'Flying'],
        image: 'assets/pokedex/384.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/384-mega.png']
    },
    {
        id: 385,
        name: 'Jirachi',
        description: "",
        type: ['Steel', 'Psychic'],
        image: 'assets/pokedex/385.png',
        mega: false,
        primal: false,
    },
    {
        id: 386,
        name: 'Deoxys',
        description: "",
        type: ['Psychic'],
        image: 'assets/pokedex/386.png',
        mega: false,
        primal: false,
    },
    {
        id: 387,
        name: 'Turtwig',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/387.png',
        mega: false,
        primal: false,
    },
    {
        id: 388,
        name: 'Grotle',
        description: "",
        type: ['Grass'],
        image: 'assets/pokedex/388.png',
        mega: false,
        primal: false,
    },
    {
        id: 389,
        name: 'Torterra',
        description: "",
        type: ['Grass', 'Ground'],
        image: 'assets/pokedex/389.png',
        mega: false,
        primal: false,
    },
    {
        id: 390,
        name: 'Chimchar',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/390.png',
        mega: false,
        primal: false,
    },
    {
        id: 391,
        name: 'Monferno',
        description: "",
        type: ['Fire', 'Fighting'],
        image: 'assets/pokedex/391.png',
        mega: false,
        primal: false,
    },
    {
        id: 392,
        name: 'Infernape',
        description: "",
        type: ['Fire', 'Fighting'],
        image: 'assets/pokedex/392.png',
        mega: false,
        primal: false,
    },
    {
        id: 393,
        name: 'Piplup',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/393.png',
        mega: false,
        primal: false,
    },
    {
        id: 394,
        name: 'Prinplup',
        description: "",
        type: ['Water'],
        image: 'assets/pokedex/394.png',
        mega: false,
        primal: false,
    },
    {
        id: 395,
        name: 'Empoleon',
        description: "",
        type: ['Water', 'Steel'],
        image: 'assets/pokedex/395.png',
        mega: false,
        primal: false,
    },
    {
        id: 398,
        name: 'Staraptor',
        description: "",
        type: ['Normal', 'Flying'],
        image: 'assets/pokedex/398.png',
        mega: false,
        primal: false,
    },
    {
        id: 445,
        name: 'Garchomp',
        description: "",
        type: ['Dragon', 'Ground'],
        image: 'assets/pokedex/445.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/445-mega.png']
    },
    {
        id: 448,
        name: 'Lucario',
        description: "",
        type: ['Fighting', 'Steel'],
        image: 'assets/pokedex/448.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/448-mega.png']
    },
    {
        id: 462,
        name: 'Magnezone',
        description: "",
        type: ['Electric', 'Steel'],
        image: 'assets/pokedex/462.png',
        mega: false,
        primal: false,
    },
    {
        id: 464,
        name: 'Rhyperior',
        description: "",
        type: ['Ground', 'Rock'],
        image: 'assets/pokedex/464.png',
        mega: false,
        primal: false,
    },
    {
        id: 466,
        name: 'Electivire',
        description: "",
        type: ['Electric'],
        image: 'assets/pokedex/466.png',
        mega: false,
        primal: false,
    },
    {
        id: 467,
        name: 'Magmortar',
        description: "",
        type: ['Fire'],
        image: 'assets/pokedex/467.png',
        mega: false,
        primal: false,
    },
    {
        id: 472,
        name: 'Gliscor',
        description: "",
        type: ['Ground', 'Flying'],
        image: 'assets/pokedex/472.png',
        mega: false,
        primal: false,
    },
    {
        id: 475,
        name: 'Gallade',
        description: "",
        type: ['Psychic', 'Fighting'],
        image: 'assets/pokedex/475.png',
        mega: true,
        primal: false,
        megaImage: ['assets/pokedex/475-mega.png']
    },
    {
        id: 477,
        name: 'Dusknoir',
        description: "",
        type: ['Ghost'],
        image: 'assets/pokedex/477.png',
        mega: false,
        primal: false,
    },
    {
        id: 483,
        name: 'Dialga',
        description: "",
        type: ['Steel', 'Dragon'],
        image: 'assets/pokedex/483.png',
        mega: false,
        primal: false,
    },
    {
        id: 484,
        name: 'Palkia',
        description: "",
        type: ['Water', 'Dragon'],
        image: 'assets/pokedex/484.png',
        mega: false,
        primal: false,
    },
    {
        id: 486,
        name: 'Regigigas',
        description: "",
        type: ['Normal'],
        image: 'assets/pokedex/486.png',
        mega: false,
        primal: false,
    },
    {
        id: 487,
        name: 'Giratina',
        description: "",
        type: ['Ghost', 'Dragon'],
        image: 'assets/pokedex/487.png',
        mega: false,
        primal: false,
    },
    {
        id: 491,
        name: 'Darkrai',
        description: "",
        type: ['Dark'],
        image: 'assets/pokedex/491.png',
        mega: false,
        primal: false,
    },
    {
        id: 493,
        name: 'Arceus',
        description: "",
        type: ['Normal'],
        image: 'assets/pokedex/493.png',
        mega: false,
        primal: false,
    }
]